name: Cross chain Arbitrum

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - "cross-chain/arbitrum/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (network) for workflow execution, e.g. `goerli`"
        required: false
      upstream_ref:
        description: "Git reference to checkout (e.g. branch name)"
        required: false
        default: "main"

jobs:
  contracts-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request'

      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './cross-chain/arbitrum/**'
              - './.github/workflows/cross-chain-arbitrum.yml'

  contracts-build-and-test:
    needs: contracts-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cross-chain/arbitrum
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: cross-chain/arbitrum/yarn.lock

      # A workaround for transitive dependencies that use the obsolete git://
      # prefix instead of the recommended https://
      - name: Configure git to not use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install

      - name: Build contracts
        run: yarn build

      - name: Run tests
        run: yarn test

  contracts-deployment-dry-run:
    needs: contracts-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cross-chain/arbitrum
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: cross-chain/arbitrum/yarn.lock

      # A workaround for transitive dependencies that use the obsolete git://
      # prefix instead of the recommended https://
      - name: Configure git to not use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy contracts
        run: yarn deploy

  contracts-deployment-testnet:
    needs: [contracts-build-and-test]
    if: |
      github.event_name == 'workflow_dispatch'
        && github.ref != 'refs/heads/dapp-development'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cross-chain/arbitrum
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: cross-chain/arbitrum/yarn.lock
          registry-url: "https://registry.npmjs.org"

      # A workaround for transitive dependencies that use the obsolete git://
      # prefix instead of the recommended https://
      - name: Configure git to not use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Resolve latest contracts
        run: yarn upgrade @keep-network/tbtc-v2@${{ github.event.inputs.environment }}

      - name: Deploy contracts
        env:
          CHAIN_API_URL: ${{ secrets.ARBITRUM_GOERLI_HOSTNAME_HTTP }}
          ACCOUNTS_PRIVATE_KEYS: ${{ secrets.ARBITRUM_GOERLI_CONTRACT_OWNER_PRIVATE_KEY }}
        run: yarn deploy --network ${{ github.event.inputs.environment }}

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          work-dir: cross-chain/arbitrum
          environment: ${{ github.event.inputs.environment }}
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public --tag ${{ github.event.inputs.environment }} --network=${{ github.event.inputs.environment }}

      - name: Notify CI about completion of the workflow
        uses: keep-network/ci/actions/notify-workflow-completed@v2
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          module: "github.com/keep-network/tbtc-v2"
          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          environment: ${{ github.event.inputs.environment }}
          upstream_builds: ${{ github.event.inputs.upstream_builds }}
          upstream_ref: ${{ github.event.inputs.upstream_ref }}
          version: ${{ steps.npm-version-bump.outputs.version }}

  contracts-format:
    needs: contracts-detect-changes
    if: |
      github.event_name == 'push'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cross-chain/arbitrum
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: cross-chain/arbitrum/yarn.lock

      # A workaround for transitive dependencies that use the obsolete git://
      # prefix instead of the recommended https://
      - name: Configure git to not use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Check formatting
        run: yarn format

  contracts-slither:
    needs: contracts-detect-changes
    if: |
      github.event_name == 'push'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cross-chain/arbitrum
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: cross-chain/arbitrum/yarn.lock

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Install Solidity
        env:
          SOLC_VERSION: 0.8.17 # according to solidity.version in hardhat.config.ts
        run: |
          pip3 install solc-select
          solc-select install $SOLC_VERSION
          solc-select use $SOLC_VERSION

      - name: Install Slither
        env:
          SLITHER_VERSION: 0.8.3
        run: pip3 install slither-analyzer==$SLITHER_VERSION

      # A workaround for transitive dependencies that use the obsolete git://
      # prefix instead of the recommended https://
      - name: Configure git to not use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Install dependencies
        run: yarn install

      - name: Run Slither
        run: slither --hardhat-artifacts-directory build .
