name: TypeScript bindings

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - "typescript/**"
  pull_request:
  workflow_dispatch:

jobs:
  typescript-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'

      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './typescript/**'

  typescript-build-and-test:
    needs: typescript-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.typescript-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: typescript/yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Tests
        run: yarn test

  typescript-format:
    needs: typescript-detect-changes
    if: |
      github.event_name == 'push'
        || needs.typescript-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: typescript/yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn format
