name: Yearn

on:
  push:
    branches:
      - main
    paths:
      - "yearn/**"
  pull_request:
  workflow_dispatch:

jobs:
  contracts-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'

      - uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './yearn/**'
  contracts-build-and-test:
    needs: contracts-detect-changes
    if: |
      github.event_name != 'pull_request'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./yearn
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install

      - name: Build contracts
        run: yarn build

      - name: Run system tests
        env:
          FORKING_URL: ${{ secrets.MAINNET_ETH_HOSTNAME }}
        run: yarn test:system

  contracts-format:
    needs: contracts-detect-changes
    if: |
      github.event_name == 'push'
        || needs.contracts-detect-changes.outputs.path-filter == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./yearn
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      # Below step is a workaround. Eslint executed in `yearn` directory
      # finds `.prettierrc.js` config in the root directory and fails if
      # referenced `@keep-network/prettier-config-keep` module is missing.
      - name: Install dependencies in the root directory
        run: |
          cd ..
          yarn install --frozen-lockfile

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn format
